# Generated by Django 4.1.7 on 2023-03-26 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Genero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Incapacidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Mascota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("fecha_nacimiento", models.DateField()),
                ("is_hembra", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="TipoMascota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Raza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=200)),
                (
                    "id_tipo_mascota",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="webapi.tipomascota",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Owner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_nacional", models.CharField(max_length=50, unique=True)),
                ("nombre", models.CharField(max_length=200)),
                ("apellido", models.CharField(max_length=200)),
                ("direccion", models.CharField(max_length=200)),
                ("telefono", models.CharField(max_length=200)),
                ("fecha_nacimiento", models.DateField()),
                ("email", models.EmailField(max_length=254)),
                (
                    "id_genero",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="webapi.genero"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MascotaIncapacidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(max_length=1000)),
                ("fecha", models.DateField()),
                (
                    "id_incapacidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="webapi.incapacidad",
                    ),
                ),
                (
                    "id_mascota",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="webapi.mascota"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MascotaColores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_color",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="webapi.color"
                    ),
                ),
                (
                    "id_mascota",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="webapi.mascota"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="mascota",
            name="id_owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="webapi.owner"
            ),
        ),
        migrations.AddField(
            model_name="mascota",
            name="id_raza",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="webapi.raza"
            ),
        ),
    ]
