# Generated by Django 4.1.7 on 2023-03-26 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="owner",
            name="id_nacional",
            field=models.CharField(max_length=50),
        ),
    ]
