# Generated by Django 4.1.7 on 2023-03-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapi", "0002_alter_owner_id_nacional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mascotaincapacidad",
            name="descripcion",
            field=models.CharField(max_length=500),
        ),
    ]
